CREATE TABLE "fiscal_decisions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "company_id" uuid NOT NULL, "codigo" text NOT NULL, "gap" text NOT NULL, "titulo" text NOT NULL, "pregunta" text NOT NULL, "alternativas" jsonb NOT NULL, "decision" text, "fundamento_normativo" text, "formula" text, "redondeo_metodo" text, "redondeo_etapa" text, "redondeo_precision" integer, "momento_fiscal" text, "ejemplo_numerico" jsonb NOT NULL DEFAULT '{}'::jsonb, "resultado_esperado" text, "moneda" text NOT NULL DEFAULT 'VES', "rule_kind" text, "concept_id" uuid, "vigencia_desde" date, "impacto_sistema" text, "status" text NOT NULL DEFAULT 'draft', "version" integer NOT NULL DEFAULT 1, "supersedes_id" uuid, "motivo" text, "firmante_nombre" text, "firmante_doc" text, "firmado_por" uuid, "firmado_en" timestamptz, "content_sha256" text, "evidencia_adjunto_id" uuid, "created_by" uuid NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "uq_decision_codigo" UNIQUE("company_id","codigo"));--> statement-breakpoint
CREATE INDEX "idx_decisions_company_status" ON "fiscal_decisions" ("company_id","status");--> statement-breakpoint
CREATE INDEX "idx_decisions_company_gap" ON "fiscal_decisions" ("company_id","gap");--> statement-breakpoint
CREATE TABLE "fiscal_decision_links" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "company_id" uuid NOT NULL, "decision_id" uuid NOT NULL, "rule_id" uuid NOT NULL, "rol" text NOT NULL, "nota" text, "created_by" uuid NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), CONSTRAINT "uq_decision_link" UNIQUE("decision_id","rule_id","rol"));--> statement-breakpoint
CREATE INDEX "idx_decision_links_rule" ON "fiscal_decision_links" ("company_id","rule_id");--> statement-breakpoint
CREATE INDEX "idx_decision_links_decision" ON "fiscal_decision_links" ("company_id","decision_id");--> statement-breakpoint
CREATE TABLE "rdf_series" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "company_id" uuid NOT NULL, "year" integer NOT NULL, "last_number" integer NOT NULL DEFAULT 0, CONSTRAINT "uq_rdf_series" UNIQUE("company_id","year"));--> statement-breakpoint
ALTER TABLE "fiscal_decisions" ADD CONSTRAINT "fk_decisions_company" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "fiscal_decisions" ADD CONSTRAINT "fk_decisions_concept" FOREIGN KEY ("concept_id") REFERENCES "withholding_concepts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "fiscal_decisions" ADD CONSTRAINT "fk_decisions_signer" FOREIGN KEY ("firmado_por") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "fiscal_decisions" ADD CONSTRAINT "fk_decisions_evidence" FOREIGN KEY ("evidencia_adjunto_id") REFERENCES "attachments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "fiscal_decisions" ADD CONSTRAINT "fk_decisions_author" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "fiscal_decisions" ADD CONSTRAINT "fk_decisions_supersedes" FOREIGN KEY ("supersedes_id") REFERENCES "fiscal_decisions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "fiscal_decision_links" ADD CONSTRAINT "fk_links_company" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "fiscal_decision_links" ADD CONSTRAINT "fk_links_decision" FOREIGN KEY ("decision_id") REFERENCES "fiscal_decisions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "fiscal_decision_links" ADD CONSTRAINT "fk_links_rule" FOREIGN KEY ("rule_id") REFERENCES "withholding_rules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "fiscal_decision_links" ADD CONSTRAINT "fk_links_author" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "rdf_series" ADD CONSTRAINT "fk_rdfseries_company" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "withholding_rules" ADD COLUMN "source_decision_id" uuid;--> statement-breakpoint
ALTER TABLE "withholding_rules" ADD CONSTRAINT "fk_rules_source_decision" FOREIGN KEY ("source_decision_id") REFERENCES "fiscal_decisions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;--> statement-breakpoint
ALTER TABLE "fiscal_decisions" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS "tenant_isolation" ON "fiscal_decisions";--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "fiscal_decisions" FOR ALL TO PUBLIC USING ("company_id" = NULLIF(current_setting('app.company_id', true), '')::uuid) WITH CHECK ("company_id" = NULLIF(current_setting('app.company_id', true), '')::uuid);--> statement-breakpoint
ALTER TABLE "fiscal_decision_links" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS "tenant_isolation" ON "fiscal_decision_links";--> statement-breakpoint
CREATE POLICY "tenant_isolation" ON "fiscal_decision_links" FOR ALL TO PUBLIC USING ("company_id" = NULLIF(current_setting('app.company_id', true), '')::uuid) WITH CHECK ("company_id" = NULLIF(current_setting('app.company_id', true), '')::uuid);--> statement-breakpoint
CREATE OR REPLACE FUNCTION rdf_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF OLD.status IN ('signed','applied','superseded') THEN IF NOT ((OLD.status = 'signed' AND NEW.status IN ('applied','superseded')) OR (OLD.status = 'applied' AND NEW.status = 'superseded')) THEN RAISE EXCEPTION 'RDF_IMMUTABLE: decisión firmada no admite edición (use supersedes_id)'; END IF; END IF; RETURN NEW; END $$;--> statement-breakpoint
DROP TRIGGER IF EXISTS trg_rdf_immutable ON "fiscal_decisions";--> statement-breakpoint
CREATE TRIGGER trg_rdf_immutable BEFORE UPDATE ON "fiscal_decisions" FOR EACH ROW EXECUTE FUNCTION rdf_immutable();
